version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            gem install bundler -v 2.1.4
            bundle check --path vendor/bundle || bundle install --deployment --with test
      - run:
          name: Setup application
          command: |
            export PATH=$PATH:"$(pwd)/bin"
            chmod +x ./bin/vendra
            vendra setup
      - run:
          name: Run rspec
          command: bundle exec rspec
      - store_test_results:
          path: test_results
